### ISSUE TITLE
jet: production mui fixture fails to BOOT in real Chromium — TypeError j is not a function (bisect this session's bundler commits)

### ISSUE THREAD

**Issue by chrischeng-c4** [chrischeng-c4/axiom#1998]
## Problem

Surfaced during #1997 verification: `tests/build/production_build_regression.rs::production_build_regression_fixture_boots_in_browser` FAILS on app/jet HEAD — the mui-visual production fixture's built bundle throws `TypeError: j is not a function` at runtime in real Chromium. Byte-identical reproduction under `JET_NO_FAST_IMPORT_SCAN=1` (same content hash `main.d3387442.js`) proves it predates #1997. The failure name pattern (single-letter identifier not a function) points at the mangle/flatten/minify family. This is a production-output correctness regression: the epic's speed numbers are void if the output doesn't run. Related but distinct: the 3 `bundler::lib_build` red tests (#1966) share a scope-isolation/JSX-identifier symptom family.

## Capability Alignment

Capability: bundler-production-build — the production corpus fixtures BOOT in real Chromium; this is the capability's core claim.
Capability Gap: a real-browser boot regression exists on HEAD with an unknown introducing commit.
Progress Evidence: recorded on this work item.

## Requirements

- R1: Deliver jet: production mui fixture fails to BOOT in real Chromium — TypeError j is not a function (bisect this session's bundler commits).
### In Scope
- BISECT first: the candidate window is this session's bundler commits on app/jet (41c53c18d dce index, aea51b4b3, 66e911a74..d0e3e5a47 e2e chain — unlikely, ae43183a9/c665fd4eb/6bea72a65/acf3d5698 splitting epic, c2394fc83/4af15c5d3 tree-shake, 8166efd76 resolver, 175770a00 cjs narrowing, 51a35d542 entry flatten, cbb1451f4 pass gates, 5f45c6453/7f8ac2ea8/a595778a2/f6c46df08 survivors, 37616b26e writes, 89fbe8867 fast scan). `git bisect` with `cargo test -p jet --test production_build_regression production_build_regression_fixture_boots_in_browser` as the oracle (build+test per step; it's a debug-profile test — feasible). Identify the first bad commit and the mechanism.
- Fix the root cause (not a band-aid): the failing symbol is a mangled single-letter binding — inspect the bundle at the throw site (the test harness prints console errors; enhance temporarily if needed) and connect to the introducing change.
- Regression protection: whatever gap let this land (the code_splitting Chromium smokes cover splitting fixtures but NOT the dom-production-build corpus family) — wire the boots-in-browser check into the routinely-run suite tier if runtime cost permits, or add the minimal missing smoke.
- Also verify whether the 3 lib_build failures (#1966) share the root cause; if yes, fix together and say so — if no, leave them to #1966.

### Out of Scope
- Speed work; new features.

## Acceptance Criteria

- AC1: introducing commit + mechanism named with evidence.
- AC2: production_build_regression 4/4 green incl. the browser boot; all other suites stay green (code_splitting 22, lazy_barrel 4, entry_flatten 5, fast_import_scan 1).
- AC3: statement on whether #1966's lib_build reds share the cause.

### Related Specs

| Spec | Relevance |
|------|-----------|
| tests/build/production_build_regression.rs | the failing gate |
| #1966 | possibly-related red family |
| epic #1990 commit list above | bisect window |

### Spec Plan

| Spec ID | Action | Main Spec Ref |
|---------|--------|---------------|
| none | none | Regression bisect + root-cause fix. |

### Verification

- AC1-AC3; dispatcher re-runs tw-monitor browser verification after the fix.

**Comment by chrischeng-c4** [comment]
Fixed in commit c12fb9cba on app/jet. Bisect + env-matrix verdict: first-bad commit f6c46df08 (survivor filter default-on) but as ESCALATOR, not origin — two general pre-existing tree_shake bugs did the damage: (1) extract_cjs_require_bindings scanned one require per LINE, dropping every subsequent require on minifier-coalesced multi-require lines (react-dom production CJS shape) — fixed with an occurrence-driven loop + position-scoped binding extraction; (2) the Step-3.5 reexport fixed point's ReexportKind::Named arm lacked the wildcard handling its Star sibling had, so barrels reached via wildcard-strength edges never propagated named default re-exports (@mui/utils clamp chain) — fixed by mirroring. Filter-off had silently over-retained past both bugs; filter-on exposed them as wrong removals (TypeError: j is not a function). production_build_regression 4/4 incl. real-Chromium boot; code_splitting 22, lazy_barrel 4, entry_flatten 5, fast_import_scan 1, tree_shake 79/79 (2 new regression tests). AC3: #1966's 3 lib_build reds are UNRELATED (lib-mode JSX scope isolation — separate family, still red, untouched). Coverage finding: the boot test existed and caught this — the gap is CI wiring (NO workflow runs cargo test -p jet on push/PR; jet-basic-dom is manual-only by design) — recommend a PR-triggered ~4s production_build_regression step; CI-architecture decision left to the maintainer. tw-monitor re-verified post-fix: builds 2.14s warm, entry 1,570KB (+3.8KB honest retention), real-browser render confirmed clean earlier this session.
